kind: Service
apiVersion: v1
metadata:
  name: {{ include "clockr.fullname" . }}-api-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "clockr.fullname" . }}-api
  ports:
    - nodePort: {{ .Values.nodePort.api }}
      port: 8080
      targetPort: 8080